### ISSUE TITLE
[BUG] NoClassDefFoundError after Dependency update

### ISSUE THREAD

**Issue by samrmur** [RocketChat/Rocket.Chat.Kotlin.SDK#112]
**Information**
After PR #106, errors thrown in the Android application which causes a crash. The application is unable to find `NamedJsonAdapter` from Kotshi. After reverting back to #103, the application ran fine.

**Error**
![image](https://user-images.githubusercontent.com/17170253/37943258-c3480bca-3144-11e8-93e9-2f39837c398a.png)

**Comment by filipedelimabrito** [comment]
Try updating the Kotshi dependency from the Android app too. 
Here is the PR from the app: https://github.com/RocketChat/Rocket.Chat.Android/pull/964

**Comment by filipedelimabrito** [comment]
Try updating the Kotshi dependency from the Android app too. 
Here is the PR from the app: https://github.com/RocketChat/Rocket.Chat.Android/pull/964
