### ISSUE TITLE
[IMPROVEMENT] "text" field missing from the ImageAttachment object

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Kotlin.SDK#186]
https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/dd15e2d55c3ca86870429b5fdb80519a1b4ba5cf/core/src/main/kotlin/chat/rocket/core/model/attachment/ImageAttachment.kt#L7

Shows a description but no "text" field. See the initial description of this issue in the Android repo: https://github.com/RocketChat/Rocket.Chat.Android/issues/1381.

@rafaelks Are you okay with adding this field and populating it when the attachment json includes a "text" field?

**Comment by rafaelks** [comment]
Yes 👍

**Comment by filipedelimabrito** [comment]
Thanks for opening this issue @bizzbyster as well as your discussion [here](https://github.com/RocketChat/Rocket.Chat.Android/issues/1381).

This is closed now by https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/189
