### ISSUE TITLE
[NEW] Add initial  support for Rich Messaging

### ISSUE THREAD

**Issue by Shailesh351** [RocketChat/Rocket.Chat.Kotlin.SDK#202]
Specification : https://github.com/WideChat/Rocket.Chat.Android/wiki/Buttons-Inside-Attachment-Object-Spec

Test : https://github.com/WideChat/Rocket.Chat.Android/wiki/(WIP)--Rich-Messaging-Acceptance-Test

**Comment by filipedelimabrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/203
