### ISSUE TITLE
[BUG] Wrong JSON key used for lastModified in Subscriptions.kt

### ISSUE THREAD

**Issue by TheGamer007** [RocketChat/Rocket.Chat.Kotlin.SDK#64]
The `lastModified` field is mapped to the `lm` key in the `Subscriptions.kt` file [here](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/model/Subscription.kt#L22). Both the documentation and the actual response received use the `ls` key.

I can send a PR, but since it's a tiny change it might be better to simply include it in a soon-to-be-merged one.

**Comment by rafaelks** [comment]
@TheGamer007 Yes, please send a PR to close this issue.
