### ISSUE TITLE
[FEATURE] Support for login with email

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Kotlin.SDK#69]
Presently the SDK supports login only with username. In order to support login with email, the payload needs to be built with the key `user` as mentioned in the [api docs](https://rocket.chat/docs/developer-guides/rest-api/authentication/login/) instead of `username` which has been used currently(see [here](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/model/LoginPayload.kt#L7)) for supporting login with username.

**Are you willing to work on this?**
Yes

**Comment by rafaelks** [comment]
@aniketsingh03 Sounds great. Thank you! 👍

**Comment by aniketsingh03** [comment]
Shall I start working on this @rafaelks ?

**Comment by rafaelks** [comment]
@aniketsingh03 Yes, please.

**Comment by aniketsingh03** [comment]
@rafael.kellermann I am getting the following log while trying to run tests for login
`Class not found: "chat.rocket.core.internal.rest.LoginTest"Empty test suite.`

**Comment by aniketsingh03** [comment]
@rafaelks I was working on this one.

**Comment by rafaelks** [comment]
@aniketsingh03 Great! Sorry about that, just removed @filipedelimabrito from assigned.
