### ISSUE TITLE
[BUG] JSON Format for Profile Update

### ISSUE THREAD

**Issue by samrmur** [RocketChat/Rocket.Chat.Kotlin.SDK#70]
While working on an issue for the Android Native application, I noticed an error (See [#762](https://github.com/RocketChat/Rocket.Chat.Android/issues/762) for an example of this error produced by [aniketsingh03](https://github.com/aniketsingh03)) that popped up when a user would attempt to update their profile. From reading the documentation for the [REST API](https://rocket.chat/docs/developer-guides/rest-api/users/update/), it looks like the payload is being delivered incorrectly. The [API](https://rocket.chat/docs/developer-guides/rest-api/users/update/) specifies that data should be delivered in this format: 
`{"userId": "BsNr28znDkG8aeo7W", "data": { "name": "new name", "email": "newemail@user.tld" }}`
However, the SDK appears to be delivering the data in this format: 
`{"userId": "BsNr28znDkG8aeo7W", "name": "new name", "email": "newemail@user.tld"}`
I observed this behaviour while looking through the LOGCAT for the [Android 2.0 App](https://github.com/RocketChat/Rocket.Chat.Android)

**Possible Fix**
Since [UserPayload](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/develop/core/src/main/kotlin/chat/rocket/core/internal/model/UserPayload.kt) is also used when signing up, it can separated into `SignUpPayload` and `UpdatePayload`.

**Willing to work on this issue**
Yes

**Comment by aniketsingh03** [comment]
@rafaelks @samrmur any update on this one?

**Comment by samrmur** [comment]
@aniketsingh03 awaiting review
