### ISSUE TITLE
[NEW] REST API to get the Custom Emojis

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Kotlin.SDK#74]

**Comment by Shailesh351** [comment]
@rafaelks Rest api available for getting custom emojis?
I can only see realtime-api for it. https://rocket.chat/docs/developer-guides/realtime-api/method-calls/list-custom-emoji/#list-custom-emoji

**Comment by rafaelks** [comment]
@Shailesh351 Yes, we do: https://github.com/RocketChat/Rocket.Chat/pull/9629.

Docs: https://github.com/RocketChat/docs/pull/550

**Comment by rafaelks** [comment]
@Shailesh351 The API isn't merged yet, but you can try based on the docs or deploy a server with that branch merged for now. When it's merged, you can try on `unstable.rocket.chat`.

**Comment by Shailesh351** [comment]
Thanks :smile: 
Can i work on this issue?

**Comment by rafaelks** [comment]
@Shailesh351 Sure thing! 👍

**Comment by leonardoaramaki** [comment]
@rafaelks Then I'll reassign the issue to @Shailesh351

**Comment by leonardoaramaki** [comment]
Ow, I can't  assign it to him...

**Comment by filipedelimabrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/196#pullrequestreview-141921050
