### ISSUE TITLE
[NEW] Rest api call for getting all members of a channel

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Kotlin.SDK#81]
Presently, the SDK does not have any rest call for fetching all members of a particular channel. In order to do so, a rest call needs to be made to the api endpoint `/api/v1/channels.members` with the params `roomName` or `roomId` and api headers `X-Auth-Token` and `X-User-Id`.

Are you willing to work on this issue?
**Yes**

**Comment by luciofm** [comment]
@aniketsingh03 this is already merged on the SDK
https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/78

**Comment by aniketsingh03** [comment]
Sorry @luciofm, my bad.
